import supabase from './db-client.js';
import {cors,identity,fail,bad,emailOf} from './_shared.js';
const statuses={proposed:'proposed',awaiting_client:'awaiting_client',awaiting_provider:'awaiting_provider',signed:'signed'};
const visible=(p,u)=>p.client_user_id===u.id||p.provider_email===emailOf(u);
const role=(p,u)=>p.client_user_id===u.id?'client':p.provider_email===emailOf(u)?'provider':null;
async function conflict(p){const {data:w,error:we}=await supabase.from('weddings').select('date').eq('id',p.wedding_id).single();if(we)throw we;const {data:ws,error:wse}=await supabase.from('weddings').select('id').eq('date',w.date);if(wse)throw wse;const ids=ws.map(x=>x.id);const {data,error}=await supabase.from('pacts').select('id,start_time,end_time,service_title').eq('provider_email',p.provider_email).eq('status','signed').in('wedding_id',ids).neq('id',p.id);if(error)throw error;return data.find(x=>x.id!==p.replaces_pact_id&&p.start_time<x.end_time&&p.end_time>x.start_time)}
export default async function handler(req,res){if(cors(req,res))return;const user=await identity(req,res);if(!user)return;try{
 if(req.method==='GET'){let query=supabase.from('pacts').select('*').order('created_at',{ascending:false});const {data,error}=await query.or(`client_user_id.eq.${user.id},provider_email.eq.${emailOf(user)}`);if(error)throw error;return res.status(200).json(data)}
 if(req.method==='POST'){const b=req.body||{};const {wedding_id,vendor_id,provider_name,provider_email,trade,service_title,description,start_time,end_time,amount,deposit,initiator_role,replaces_pact_id}=b;if(!wedding_id||!provider_name?.trim()||!service_title?.trim()||!start_time||!end_time||start_time>=end_time||Number(amount)<0||!Number.isFinite(Number(amount)))return bad(res,'Vérifiez les parties, la prestation, le prix et les horaires.');const {data:w}=await supabase.from('weddings').select('*').eq('id',wedding_id).maybeSingle();if(!w)return bad(res,'Mariage introuvable. Vérifiez le code du mariage.');const isClient=w.owner_id===user.id;const actualEmail=isClient?provider_email?.trim().toLowerCase():emailOf(user);if(!actualEmail?.includes('@'))return bad(res,'E-mail du prestataire invalide.');const isProvider=emailOf(user)===actualEmail;if(!isClient&&!isProvider)return res.status(403).json({error:'Vous devez être le couple ou le prestataire indiqué.'});if(initiator_role!==(isClient?'client':'provider'))return bad(res,'Initiateur invalide.');if(Number(deposit||0)>Number(amount))return bad(res,'L’acompte ne peut pas dépasser le montant total.');let vendor=null;if(vendor_id){const {data}=await supabase.from('vendors').select('id').eq('id',vendor_id).eq('wedding_id',wedding_id).maybeSingle();vendor=data;if(!vendor)return bad(res,'Prestataire invalide.')}
 let old=null;if(replaces_pact_id){const result=await supabase.from('pacts').select('*').eq('id',replaces_pact_id).maybeSingle();old=result.data;if(!old||!['signed','proposed','awaiting_client','awaiting_provider'].includes(old.status)||old.wedding_id!==wedding_id||old.provider_email!==actualEmail||!visible(old,user))return bad(res,'PACTE d’origine invalide.');}
 const {data,error}=await supabase.from('pacts').insert({wedding_id,vendor_id:vendor?.id||null,initiator_role,client_user_id:w.owner_id,provider_user_id:isProvider?user.id:null,provider_email:actualEmail,provider_name:provider_name.trim(),trade:trade?.trim()||'',service_title:service_title.trim(),description:description?.trim()||'',start_time,end_time,amount:Number(amount),deposit:Number(deposit||0),status:'proposed',replaces_pact_id:replaces_pact_id||null}).select('*').single();if(error)throw error;if(old&&old.status!=='signed'){const {data:replaced,error:replaceError}=await supabase.from('pacts').update({status:'superseded',updated_at:new Date().toISOString()}).eq('id',old.id).eq('status',old.status).select('id').maybeSingle();if(replaceError||!replaced){await supabase.from('pacts').delete().eq('id',data.id);return res.status(409).json({error:'Le PACTE a changé entre-temps. Actualisez la page.'})}}return res.status(201).json(data)}
 if(req.method==='PUT'){const {id,action}=req.body||{};const {data:p,error:pe}=await supabase.from('pacts').select('*').eq('id',id||'00000000-0000-0000-0000-000000000000').maybeSingle();if(pe)throw pe;if(!p||!visible(p,user))return res.status(403).json({error:'Accès refusé.'});if(action==='reject'){if(!['proposed','awaiting_client','awaiting_provider'].includes(p.status))return bad(res,'Seule une proposition non finalisée peut être refusée.');const {data,error}=await supabase.from('pacts').update({status:'rejected',updated_at:new Date().toISOString()}).eq('id',id).eq('status',p.status).select('*').maybeSingle();if(error)throw error;if(!data)return res.status(409).json({error:'Le PACTE a changé. Actualisez la page.'});return res.status(200).json(data)}if(action!=='sign')return bad(res,'Action inconnue. Les PACTEs signés ne sont jamais modifiés directement.');if(!Object.values(statuses).includes(p.status)||p.status==='signed')return bad(res,'Ce PACTE ne peut pas être signé.');const side=role(p,user);if(side==='client'&&p.client_signed_at||side==='provider'&&p.provider_signed_at)return bad(res,'Vous avez déjà signé ce PACTE.');const now=new Date().toISOString();const both=side==='client'?!!p.provider_signed_at:!!p.client_signed_at;
 if(both){const overlapping=await conflict(p);if(overlapping)return res.status(409).json({error:`Conflit d’horaire avec « ${overlapping.service_title} ». Le prestataire est déjà engagé sur ce créneau.`});}
 const patch=side==='client'?{client_signed_at:now}:{provider_signed_at:now,provider_user_id:user.id};patch.status=both?'signed':side==='client'?'awaiting_provider':'awaiting_client';patch.updated_at=now;
 const {data,error}=await supabase.from('pacts').update(patch).eq('id',id).eq('status',p.status).select('*').maybeSingle();if(error)throw error;if(!data)return res.status(409).json({error:'Ce PACTE vient de changer. Actualisez la page.'});if(both&&p.replaces_pact_id){await supabase.from('pacts').update({status:'superseded',updated_at:now}).eq('id',p.replaces_pact_id).eq('status','signed');}
 return res.status(200).json(data)}
 return res.status(405).json({error:'Méthode non autorisée.'});
 }catch(e){fail(res,e)}}
