import supabase from './db-client.js';
import {cors,identity,fail,bad,emailOf} from './_shared.js';
export default async function handler(req,res){if(cors(req,res))return;const user=await identity(req,res);if(!user)return;try{
 if(req.method==='GET'){const wedding_id=req.query.wedding_id;if(wedding_id){const {data:w}=await supabase.from('weddings').select('id').eq('id',wedding_id).eq('owner_id',user.id).maybeSingle();if(!w)return res.status(403).json({error:'Accès refusé.'});const [{data:items,error:e1},{data:pacts,error:e2}]=await Promise.all([supabase.from('timeline_items').select('*').eq('wedding_id',wedding_id).order('time'),supabase.from('pacts').select('*').eq('wedding_id',wedding_id).eq('status','signed').order('start_time')]);if(e1||e2)throw e1||e2;return res.status(200).json({items,pacts})}
 const {data:pacts,error}=await supabase.from('pacts').select('*').eq('status','signed').eq('provider_email',emailOf(user)).order('start_time');if(error)throw error;const ids=[...new Set(pacts.map(p=>p.wedding_id))];let weddings=[];if(ids.length){const result=await supabase.from('weddings').select('id,partner_names,date,venue').in('id',ids);if(result.error)throw result.error;weddings=result.data}return res.status(200).json({items:[],pacts,weddings})}
 const {wedding_id,id,time,title}=req.body||{};const {data:w}=await supabase.from('weddings').select('id').eq('id',wedding_id||'00000000-0000-0000-0000-000000000000').eq('owner_id',user.id).maybeSingle();if(!w)return res.status(403).json({error:'Accès refusé.'});
 if(req.method==='POST'){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time||'')||!title?.trim())return bad(res,'Heure et intitulé valides requis.');const {data,error}=await supabase.from('timeline_items').insert({wedding_id,time,title:title.trim()}).select('*').single();if(error)throw error;return res.status(201).json(data)}
 if(req.method==='PUT'){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time||'')||!title?.trim())return bad(res,'Heure et intitulé valides requis.');const {data,error}=await supabase.from('timeline_items').update({time,title:title.trim()}).eq('id',id).eq('wedding_id',wedding_id).select('*').single();if(error)throw error;return res.status(200).json(data)}
 if(req.method==='DELETE'){const {error}=await supabase.from('timeline_items').delete().eq('id',id).eq('wedding_id',wedding_id);if(error)throw error;return res.status(200).json({ok:true})}
 return res.status(405).json({error:'Méthode non autorisée.'});
 }catch(e){fail(res,e)}}
