import supabase from './db-client.js';
import {cors,identity,fail,bad} from './_shared.js';
const defaults=[['10:00','Préparatifs'],['12:00','Cérémonie'],['13:30','Cocktail'],['19:30','Dîner'],['22:30','Soirée']];
export default async function handler(req,res){if(cors(req,res))return;const user=await identity(req,res);if(!user)return;try{
 if(req.method==='GET'){const {data,error}=await supabase.from('weddings').select('*').eq('owner_id',user.id).order('created_at',{ascending:false});if(error)throw error;return res.status(200).json(data)}
 if(req.method==='POST'){const {partner_names,date,venue}=req.body||{};if(!partner_names?.trim()||!date||!venue?.trim())return bad(res,'Renseignez les prénoms, la date et le lieu.');const {data,error}=await supabase.from('weddings').insert({owner_id:user.id,partner_names:partner_names.trim(),date,venue:venue.trim()}).select('*').single();if(error)throw error;const {error:timelineError}=await supabase.from('timeline_items').insert(defaults.map(([time,title])=>({wedding_id:data.id,time,title})));if(timelineError)throw timelineError;return res.status(201).json(data)}
 if(req.method==='PUT'){const {id,partner_names,date,venue}=req.body||{};const {data:old}=await supabase.from('weddings').select('id,partner_names,date,venue').eq('id',id).eq('owner_id',user.id).maybeSingle();if(!old)return res.status(403).json({error:'Accès refusé.'});if(!partner_names?.trim()||!date||!venue?.trim())return bad(res,'Tous les champs sont requis.');if(old.partner_names!==partner_names.trim()||old.date!==date||old.venue!==venue.trim()){const {data:active,error:checkError}=await supabase.from('pacts').select('id').eq('wedding_id',id).eq('status','signed').limit(1);if(checkError)throw checkError;if(active?.length)return bad(res,'Ce mariage a un PACTE signé. Pour préserver le document, traitez le changement avec vos prestataires avant de modifier les détails du mariage.')}const {data,error}=await supabase.from('weddings').update({partner_names:partner_names.trim(),date,venue:venue.trim()}).eq('id',id).select('*').single();if(error)throw error;return res.status(200).json(data)}
 return res.status(405).json({error:'Méthode non autorisée.'});
 }catch(e){fail(res,e)}}
